ttle = "Koh Yamakawa"
#Commented out so that doesn't repeat baseURL with menu items
#baseURL = "kohtaroyamakawa.github.io"
languageCode = "en-us"
theme = "hugo-coder"
themesDir = "./themes/"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
Paginate = 10 
googleAnalytics = "G-STR339FTKR"
enableRobotsTXT = true

colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
#hideColorSchemeToggle = false
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.renderer]
#      unsafe = true
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/posts"
    weight = 3
  [[menu.main]]
    name = "Taiko"
    url = "/abouttaiko"
    weight = 5
#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"
[params]
    author = "Koh Yamakawa"
    description = "Koh's personal website"
    keywords = "physicist, taiko artist, coffee addict"
    info = "PhD student at UC Berkeley"
    avatarURL = "img/kohavatar.png"
    body_classes = "georgia bg-near-white"
    #body_classes = "Inconsolata"
    favicon = "img/kohavatar.png"
    site_logo = "img/kohavatar.png"
    email                    = "kohtaro_yamakawa@berkeley.edu"
    github                   = "//github.com/kohtaroyamakawa"

[[params.social]]
name = "Email"
icon = "fa fa-envelope"
weight = 1
url = "kohtaro_yamakawa@berkeley.edu"
[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 2
url = "https://github.com/kohtaroyamakawa/"    
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    featured_image = "/img/qm.jpeg"
    featured_image_caption =  "Getty Images/iStockphoto"
    recent_posts_number = 2
    summaryLength = 0
