title = "Koh Yamakawa"
#Commented out so that doesn't repeat baseURL with menu items
#baseURL = "kohtaroyamakawa.github.io"
languageCode = "en-us"
#theme = "ananke"
theme = "hugo-coder"
themesDir = "./themes/"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Taiko"
    url = "/abouttaiko"
    weight = 3
  [[menu.main]]
    name = "Bookshelf"
    url = "/bookshelf"
    weight = 3
#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"

[params]
author = "Koh Yamakawa"
description = "Koh's personal website"
keywords = "physicist, taiko artist, coffee addict"
info = "PhD student at UC Berkeley"
avatarURL = "img/kohavatar.png"
    body_classes = "georgia bg-near-white"
  favicon = "img/kohavatar.png"
  site_logo = "img/kohavatar.png"
#  facebook = ""
  email                    = "kohtaro_yamakawa@berkeley.edu"
  github                   = "//github.com/kohtaroyamakawa"
#  linkedin                 = "//linkedin.com/in/justin-wong-23155411b"

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/qm.jpeg"
  featured_image_caption =  "Getty Images/iStockphoto"
  recent_posts_number = 2
    summaryLength = 0
